// ==================== THREAT IDENTITY / REGENERATION MERGE ====================
// Single Responsibility: preserve analyst-owned data across a FULL threat
// regeneration.
//
// Background
// ----------
// The full-regeneration path (ElementThreatGenerator / InteractionThreatGenerator
// generateThreatsForProject) rebuilds every threat from scratch via
// createEmptyThreat(). It has no lookup against the previously generated set, so
// any analyst-owned field (relevance rating, eval note, mitigation/verification
// notes, custom no-id entries, threat actor, analyst-customised text) is silently
// discarded on every regeneration — most visibly after a DFD renumber, which is
// what triggers a regeneration in the first place.
//
// The "silent" DFD-change sync path (element-sync.ts / interaction-sync.ts) is
// already non-destructive; only the full regeneration loses data. This module is
// the missing merge step for that path.
//
// Design
// ------
// A threat is matched to its predecessor by a STABLE NATURAL KEY built from the
// DFD reference it carries — NOT by threat.id (which is derived from the mutable
// display id and therefore changes on renumber). Both the "existing" index and
// the "generated" lookup compute the key from the same fields, so the match is
// renumber-proof.
//
//   per-element   : (linkedElement.elementId, strideCategory)
//   per-interaction, data-flow : (dataFlow.connectionId, strideCategory, direction)
//   per-interaction, interface : (linkedElement.elementId, strideCategory)
//
// linkedElement.elementId / dataFlow.connectionId are stable DFD UUIDs and are
// present on every generated threat regardless of the display-id format, so the
// merge works on projects saved BEFORE any identity change — no migration needed.

import type {
  Threat,
  ThreatTable,
  MitigationDraft,
  VerificationDraft,
} from "../models/threat-types";

// ==================== NATURAL KEYS ====================

/**
 * Stable natural key for a per-element-method threat.
 *
 * Covers normal elements, interfaces AND data-flow threats generated by the
 * per-element method — all of them set linkedElement, whose elementId is the
 * stable DFD element / connection UUID. Returns null for a threat with no
 * linked element (e.g. a manually created threat with no DFD anchor); such
 * threats are never emitted by the generator and are therefore never merged.
 */
export function elementThreatNaturalKey(threat: Threat): string | null {
  const elementId = threat.linkedElement?.elementId;
  if (!elementId) return null;
  return `${elementId}::${threat.strideCategory}`;
}

/**
 * Stable natural key for a per-interaction-method threat.
 *
 * Data-flow threats include the direction because the sender and receiver
 * perspectives of one connection are two independent threats. Interface threats
 * (per-interaction) use linkedElement and a fixed "incoming" direction, so they
 * key on (elementId, strideCategory) like the per-element case.
 */
export function interactionThreatNaturalKey(threat: Threat): string | null {
  const connectionId = threat.dataFlow?.connectionId;
  if (connectionId) {
    const direction = threat.interactionContext?.direction ?? "";
    return `df::${connectionId}::${threat.strideCategory}::${direction}`;
  }
  const elementId = threat.linkedElement?.elementId;
  if (elementId) {
    return `el::${elementId}::${threat.strideCategory}`;
  }
  return null;
}

// ==================== INDEX ====================

/**
 * Index a set of threat tables by natural key. First occurrence wins — the
 * generator's own end-of-run dedup guarantees at most one threat per key, so a
 * collision here would only mean pre-existing duplicate residue in a loaded
 * file, in which case keeping the first is the safe choice.
 */
export function buildThreatIndex(
  tables: ThreatTable[] | undefined,
  keyFn: (threat: Threat) => string | null,
): Map<string, Threat> {
  const index = new Map<string, Threat>();
  if (!tables) return index;
  for (const table of tables) {
    for (const threat of table.threats) {
      const key = keyFn(threat);
      if (key && !index.has(key)) index.set(key, threat);
    }
  }
  return index;
}

// ==================== FIELD-LEVEL MERGE ====================

/**
 * Merge proposed mitigations across a regeneration.
 *
 * The close-loop drift flags (alreadyImplemented / implementedByProperty /
 * implementedByValue) MUST always be recomputed — they reflect live DFD model
 * state — so they are taken from `fresh`. Only the analyst's free-text `notes`
 * on catalogue (id-bearing) entries are carried over, and any fully custom
 * (no-id) analyst entries are appended unchanged.
 */
export function mergeProposedMitigations(
  existing: MitigationDraft[] | undefined,
  fresh: MitigationDraft[],
): MitigationDraft[] {
  const priorById = new Map<string, MitigationDraft>();
  const priorCustom: MitigationDraft[] = [];
  for (const m of existing ?? []) {
    if (m.id) priorById.set(m.id, m);
    else priorCustom.push(m);
  }

  const mergedCatalogue = fresh.map((f) => {
    if (!f.id) return f;
    const prior = priorById.get(f.id);
    if (!prior || prior.notes === undefined) return f;
    // Keep fresh derived flags; carry over the analyst note.
    return { ...f, notes: prior.notes };
  });

  return [...mergedCatalogue, ...priorCustom];
}

/**
 * Verification equivalent of mergeProposedMitigations. VerificationDraft has no
 * derived flags, so this is purely: carry over notes on catalogue entries,
 * append custom entries.
 */
export function mergeProposedVerifications(
  existing: VerificationDraft[] | undefined,
  fresh: VerificationDraft[],
): VerificationDraft[] {
  const priorById = new Map<string, VerificationDraft>();
  const priorCustom: VerificationDraft[] = [];
  for (const v of existing ?? []) {
    if (v.id) priorById.set(v.id, v);
    else priorCustom.push(v);
  }

  const mergedCatalogue = fresh.map((f) => {
    if (!f.id) return f;
    const prior = priorById.get(f.id);
    if (!prior || prior.notes === undefined) return f;
    return { ...f, notes: prior.notes };
  });

  return [...mergedCatalogue, ...priorCustom];
}

// ==================== THREAT-LEVEL MERGE ====================

/**
 * Overlay analyst-owned fields from a previously generated threat onto a freshly
 * regenerated one.
 *
 * `existing === undefined` → the threat is genuinely new; `fresh` is returned
 * unchanged.
 *
 * STABLE IDENTITY (preserved from `existing`): id (the UUID). A regeneration
 * mints a fresh UUID on every threat via createEmptyThreat(); when the threat
 * already existed we keep its original UUID so all cross-references
 * (Risk.threatId, AttackTreeAnchor.threatId, table row keys) stay intact.
 *
 * SYSTEM-DERIVED (always from `fresh`, via the spread): displayId (the
 * regenerated label), linkedElement, dataFlow, interactionContext,
 * trustBoundary*, linkedAssetIds, initialImpact, source, templateId,
 * causeDescription, sequenceNumber.
 *
 * ANALYST-OWNED (preserved from `existing`): relevance, workflowStatus,
 * evalNote, threatActor, isTextCustomized (+ the customised threat/attack text
 * when that flag is set), mitigation/verification notes and custom entries.
 *
 * created / lastModified are preserved from `existing` so that a no-op
 * regeneration is byte-stable (no audit-trail churn) — a regeneration is a
 * system action, not an analyst edit, and analyst edits set lastModified
 * through the dialog save path.
 */
export function mergeGeneratedThreat(
  existing: Threat | undefined,
  fresh: Threat,
): Threat {
  if (!existing) return fresh;

  const keepCustomText = existing.isTextCustomized === true;

  return {
    ...fresh,

    // ── Stable identity: keep the original UUID (fresh has a brand-new one) ─
    id: existing.id,

    // ── Analyst-owned: always preserved ──────────────────────────────────
    relevance: existing.relevance,
    workflowStatus: existing.workflowStatus,
    evalNote: existing.evalNote,
    threatActor: existing.threatActor,
    isTextCustomized: existing.isTextCustomized,
    threatDescription: keepCustomText
      ? existing.threatDescription
      : fresh.threatDescription,
    attackDescription: keepCustomText
      ? existing.attackDescription
      : fresh.attackDescription,
    proposedMitigations: mergeProposedMitigations(
      existing.proposedMitigations,
      fresh.proposedMitigations,
    ),
    proposedVerifications: mergeProposedVerifications(
      existing.proposedVerifications,
      fresh.proposedVerifications,
    ),

    // ── Timestamps: preserved so a no-op regen produces no diff ──────────
    created: existing.created ?? fresh.created,
    lastModified: existing.lastModified ?? fresh.lastModified,
  };
}

// ==================== TABLE-LEVEL MERGE ====================

/**
 * Apply mergeGeneratedThreat across every threat in a freshly generated set,
 * matched against the previously generated tables by natural key. This is the
 * single call the generators make after building their fresh tables.
 */
/**
 * Keep only analyst-authored (`source === "manual"`) threats, dropping tables
 * that become empty. Used by "Delete all threats" when the analyst chose to
 * preserve manual threats — mirrors the keepManual behaviour of
 * mergeGeneratedTables, but for a plain deletion rather than a regeneration.
 */
export function retainManualThreatTables(tables: ThreatTable[]): ThreatTable[] {
  return tables
    .map((table) => ({
      ...table,
      threats: table.threats.filter((t) => t.source === "manual"),
    }))
    .filter((table) => table.threats.length > 0);
}

export interface MergeGeneratedTablesOptions {
  /**
   * When true, analyst-authored threats (`source === "manual"`) present in the
   * previous tables are carried over into the regenerated set instead of being
   * dropped. The generator never emits manual threats, so without this they
   * would simply disappear on regeneration. Manual threats are re-attached to
   * the fresh table sharing their trust-boundary grouping; those whose grouping
   * no longer exists (element/boundary deleted) are preserved in a carried-over
   * table so nothing is lost silently. Defaults to false (drop manual threats).
   */
  keepManual?: boolean;
}

export function mergeGeneratedTables(
  freshTables: ThreatTable[],
  previousTables: ThreatTable[] | undefined,
  keyFn: (threat: Threat) => string | null,
  options: MergeGeneratedTablesOptions = {},
): ThreatTable[] {
  const index = buildThreatIndex(previousTables, keyFn);

  const merged =
    index.size === 0
      ? freshTables
      : freshTables.map((table) => ({
          ...table,
          threats: table.threats.map((fresh) => {
            const key = keyFn(fresh);
            return mergeGeneratedThreat(key ? index.get(key) : undefined, fresh);
          }),
        }));

  if (!options.keepManual || !previousTables) return merged;

  return reattachManualThreats(merged, previousTables);
}

/** Grouping key for matching a manual threat's previous table to a fresh one. */
function tableGroupKey(table: ThreatTable): string {
  return `${table.trustBoundaryId ?? "∅"}::${table.displayIdentifier}`;
}

/**
 * Re-attach `source === "manual"` threats from the previous tables into the
 * regenerated set. A manual threat is appended to the fresh table sharing its
 * previous table's grouping; if no such fresh table exists, its previous table
 * is carried over (holding only its manual threats) so the analyst's work is
 * never lost silently. Manual threats intentionally coexist with a generated
 * threat of the same element+STRIDE — they are distinct analyst-authored rows,
 * not duplicates, so they are appended rather than merged by natural key.
 */
function reattachManualThreats(
  freshTables: ThreatTable[],
  previousTables: ThreatTable[],
): ThreatTable[] {
  const manualByGroup = new Map<string, Threat[]>();
  for (const table of previousTables) {
    const manual = table.threats.filter((t) => t.source === "manual");
    if (manual.length === 0) continue;
    const key = tableGroupKey(table);
    const bucket = manualByGroup.get(key);
    if (bucket) bucket.push(...manual);
    else manualByGroup.set(key, [...manual]);
  }
  if (manualByGroup.size === 0) return freshTables;

  const consumed = new Set<string>();
  const withManual = freshTables.map((table) => {
    const key = tableGroupKey(table);
    const manual = manualByGroup.get(key);
    if (!manual) return table;
    consumed.add(key);
    return { ...table, threats: [...table.threats, ...manual] };
  });

  // Manual threats whose grouping no longer exists in the fresh set: preserve
  // them in a carried-over table rather than dropping them.
  for (const table of previousTables) {
    const key = tableGroupKey(table);
    if (consumed.has(key) || !manualByGroup.has(key)) continue;
    consumed.add(key);
    withManual.push({
      ...table,
      threats: manualByGroup.get(key)!,
    });
  }

  return withManual;
}
