// ==================== AUDIT REPO — GITIGNORE GUARD ====================
// The managed git hook lives in `.tara/hooks/` and is wired via a LOCAL,
// never-committed `core.hooksPath`. It is non-authoritative (the audit CLI/CI
// with a pinned anchor is authoritative), per-machine, and regenerated by the
// app per HOOKS_VERSION — so it must NOT be committed. This guard keeps a
// TARAflow-managed block in the repo's `.gitignore` that ignores `.tara/hooks/`,
// so the hook never shows up as an untracked/committable file.
//
// IMPORTANT: only `.tara/hooks/` is ignored. The REST of `.tara/` — the signer
// manifest `.tara/allowed_signers` (the trust root, read from history; the
// audit anchor is the commit that adds it) and a future `.tara/policy.json` —
// MUST stay tracked. Never ignore `.tara/` wholesale.
//
// Same shape as audit-repo-attributes.ts: pure logic + injected side effects
// (git runner, fs). The authoritative "is it ignored?" check uses
// `git check-ignore`, honouring global/nested ignore rules — we never
// hand-parse `.gitignore` to decide whether the requirement is satisfied. The
// COMMIT of the changed `.gitignore` is done by the caller (hook-install flow),
// reusing the single git path, so this module stays free of commit concerns.

import type { GitRunner, FileIO } from "./audit-repo-attributes";

// ── Contract ───────────────────────────────────────────────────────────────

/** Repo-root-anchored path(s) the managed block ignores. Only the hooks dir. */
export const IGNORED_PATHS: ReadonlyArray<string> = ["/.tara/hooks/"];

/** A path under the ignored dir, used to probe `git check-ignore`. */
const PROBE_HOOK_PATH = ".tara/hooks/commit-msg";

/** The tracked hook path we defensively un-track if it was ever committed. */
export const HOOK_REL_PATH = ".tara/hooks/commit-msg";

/** Marker identifying the block TARAflow manages, so appends stay idempotent. */
export const IGNORE_MANAGED_BLOCK_MARKER =
  "# TARAflow: local audit tooling, do not commit (managed)";

/** `<repoRoot>/.gitignore`, using the separator the root already uses. */
export function gitignorePathOf(repoRoot: string): string {
  const sep = repoRoot.includes("\\") ? "\\" : "/";
  return repoRoot.replace(/[/\\]+$/, "") + sep + ".gitignore";
}

// ── Pure helpers (unit-tested directly) ──────────────────────────────────────

/** The block TARAflow appends to a repo's .gitignore. */
export function taraIgnoreBlock(): string {
  return [IGNORE_MANAGED_BLOCK_MARKER, ...IGNORED_PATHS, ""].join("\n");
}

export function hasManagedBlock(existing: string | null): boolean {
  return !!existing && existing.includes(IGNORE_MANAGED_BLOCK_MARKER);
}

/**
 * Return .gitignore content with the managed block appended.
 * Idempotent: if the marker is already present, returns the input unchanged.
 * Preserves existing content (e.g. the user's own `*.backup.json`, `diff*.txt`)
 * and avoids stray blank lines.
 */
export function withTaraIgnoreAppended(existing: string | null): string {
  if (hasManagedBlock(existing)) return existing as string;
  const base =
    existing && existing.length > 0
      ? existing.endsWith("\n")
        ? existing
        : existing + "\n"
      : "";
  const sep = base.length > 0 ? "\n" : "";
  return base + sep + taraIgnoreBlock();
}

// ── Orchestration (side-effecting, thin) ─────────────────────────────────────

/** True if git's ignore rules currently ignore the hooks dir (any source). */
export async function isHooksDirIgnored(
  run: GitRunner,
  repoPath: string,
): Promise<boolean> {
  // `git check-ignore -q <path>` → exit 0 when the path is ignored, 1 when not.
  const res = await run(["check-ignore", "-q", PROBE_HOOK_PATH], repoPath);
  return res.code === 0;
}

/** True if the hook file is tracked (was committed before) → needs untracking. */
export async function isHookTracked(
  run: GitRunner,
  repoPath: string,
): Promise<boolean> {
  // `--error-unmatch` exits non-zero when the path is NOT tracked.
  const res = await run(
    ["ls-files", "--error-unmatch", HOOK_REL_PATH],
    repoPath,
  );
  return res.code === 0;
}

export interface IgnoreStatus {
  /** True only if the hooks dir is ignored AND the hook is not tracked. */
  ok: boolean;
  /** git's ignore rules currently cover `.tara/hooks/`. */
  ignored: boolean;
  /** A TARAflow-managed block already exists in the repo .gitignore. */
  managedBlockPresent: boolean;
  /** The hook file is tracked and must be `git rm --cached`d. */
  hookTracked: boolean;
  /** Whether the caller must commit a `.gitignore` change and/or an untrack. */
  needsCommit: boolean;
}

/** Inspect whether the audit repo ignores its local hooks dir. */
export async function inspectAuditRepoIgnore(
  run: GitRunner,
  io: FileIO,
  repoPath: string,
  gitignorePath: string,
): Promise<IgnoreStatus> {
  const ignored = await isHooksDirIgnored(run, repoPath);
  const hookTracked = await isHookTracked(run, repoPath);
  const existing = await io.read(gitignorePath);
  const managedBlockPresent = hasManagedBlock(existing);
  return {
    ok: ignored && !hookTracked,
    ignored,
    managedBlockPresent,
    hookTracked,
    needsCommit: !managedBlockPresent || hookTracked,
  };
}

export interface ApplyIgnoreResult {
  status: IgnoreStatus;
  /** The .gitignore was written (managed block newly appended). */
  gitignoreChanged: boolean;
  /** The hook was un-tracked via `git rm --cached`. */
  untracked: boolean;
  /** Repo-relative paths the caller should stage + commit (may be empty). */
  toStage: string[];
}

/**
 * Ensure `.tara/hooks/` is ignored: append the managed block if missing, and
 * defensively `git rm --cached` the hook if it was ever tracked. Write-only +
 * index-only side effects — the caller COMMITS the returned `toStage` paths
 * (path-scoped `audit:` commit), keeping this module off the commit path.
 */
export async function applyAuditRepoIgnore(
  run: GitRunner,
  io: FileIO,
  repoPath: string,
  gitignorePath: string,
): Promise<ApplyIgnoreResult> {
  const toStage: string[] = [];

  const existing = await io.read(gitignorePath);
  let gitignoreChanged = false;
  if (!hasManagedBlock(existing)) {
    await io.write(gitignorePath, withTaraIgnoreAppended(existing));
    gitignoreChanged = true;
    toStage.push(".gitignore");
  }

  // Untrack the hook if it slipped into history before it was ignored. `git rm
  // --cached` removes it from the index only; the working-tree file (and the
  // live hook) stay in place. Its deletion is part of the same commit.
  let untracked = false;
  if (await isHookTracked(run, repoPath)) {
    const rm = await run(
      ["rm", "--cached", "--ignore-unmatch", HOOK_REL_PATH],
      repoPath,
    );
    if (rm.code === 0) {
      untracked = true;
      toStage.push(HOOK_REL_PATH);
    }
  }

  const status = await inspectAuditRepoIgnore(run, io, repoPath, gitignorePath);
  return { status, gitignoreChanged, untracked, toStage };
}

/** The commit subject the caller should use for the ignore/untrack commit. */
export const IGNORE_COMMIT_SUBJECT =
  "audit: ignore local .tara/hooks (managed, non-authoritative)";
